version: '3.4'

services:
  prueba.tecnica.api:
    image: ${DOCKER_REGISTRY-}pruebatecnicaapi
    build:
      context: .
      dockerfile: Prueba.Tecnica.API/Dockerfile
    networks:
      - prueba

  postgres-prueba:
    image: postgres:14
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    networks:
      - prueba
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres-prueba
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data 